### ISSUE TITLE
StackOverflowError

### ISSUE THREAD

**Issue by MartinOtter** [SciML/DiffEqBase.jl#784]
Before releasing a new Modia version, I made "update", but then I get a **StackOverflowError**. To find the reason, I used the latest released Modia version from github and then made update. Comparing the Modia [manifest file](https://github.com/ModiaSim/Modia.jl/blob/main/Manifest.toml) with the updated environments manifest file shows:

- DifferentialEquations.jl 7.1.0 for both
- **DiffEqBase: 6.82.0** and after update **6.91.6**

The Julia Stacktrace is:

```julia
ERROR: LoadError: StackOverflowError:
Stacktrace:
      [1] #names#8
        @ .\reflection.jl:102 [inlined]
      [2] names
        @ .\reflection.jl:102 [inlined]
      [3] propertynames
        @ .\reflection.jl:1665 [inlined]
      [4] anyeltypedual(x::Module)
        @ DiffEqBase .julia\packages\DiffEqBase\SaKTs\src\forwarddiff.jl:51
      [5] (::DiffEqBase.var"#81#82"{Module})(y::Symbol)
        @ DiffEqBase .julia\packages\DiffEqBase\SaKTs\src\forwarddiff.jl:54
      [6] mapreduce_first
        @ .\reduce.jl:394 [inlined]
      [7] _mapreduce(f::DiffEqBase.var"#81#82"{Module}, op::typeof(DiffEqBase.promote_dual), #unused#::IndexLinear, A::Vector{Symbol})
        @ Base .\reduce.jl:405
      [8] _mapreduce_dim
        @ .\reducedim.jl:330 [inlined]
      [9] #mapreduce#725
        @ .\reducedim.jl:322 [inlined]
     [10] mapreduce
        @ .\reducedim.jl:322 [inlined]
     [11] anyeltypedual(x::Module)
        @ DiffEqBase .julia\packages\DiffEqBase\SaKTs\src\forwarddiff.jl:54
--- the last 7 lines are repeated 15345 more times ---
 [107427] (::DiffEqBase.var"#81#82"{SimulationModel{Float64, Float64}})(y::Symbol)
        @ DiffEqBase .julia\packages\DiffEqBase\SaKTs\src\forwarddiff.jl:54
 [107428] MappingRF
        @ .\reduce.jl:95 [inlined]
 [107429] afoldl(::Base.MappingRF{DiffEqBase.var"#81#82"{SimulationModel{Float64, Float64}}, Base.BottomRF{typeof(DiffEqBase.promote_dual)}}, ::Base._InitialValue, ::Symbol, ::Symbol, ::Symbol, ::Symbol, ::Symbol, ::Symbol, ::Symbol, ::Symbol, ::Symbol, ::Symbol, ::Symbol, ::Symbol, ::Symbol, ::Symbol, ::Symbol, ::Symbol, ::Symbol, ::Symbol, ::Symbol, ::Symbol, ::Symbol, ::Symbol, ::Symbol, ::Symbol, ::Symbol, ::Symbol, ::Symbol, ::Symbol, ::Symbol, ::Symbol, ::Symbol, ::Symbol, ::Vararg{Symbol})
        @ Base .\operators.jl:612
 [107430] _foldl_impl
        @ .\tuple.jl:277 [inlined]
 [107431] foldl_impl
        @ .\reduce.jl:48 [inlined]
 [107432] mapfoldl_impl
        @ .\reduce.jl:44 [inlined]
 [107433] #mapfoldl#244
        @ .\reduce.jl:162 [inlined]
 [107434] mapfoldl
        @ .\reduce.jl:162 [inlined]
 [107435] #mapreduce#248
        @ .\reduce.jl:289 [inlined]
 [107436] mapreduce
        @ .\reduce.jl:289 [inlined]
 [107437] anyeltypedual
        @ .julia\packages\DiffEqBase\SaKTs\src\forwarddiff.jl:54 [inlined]
 [107438] promote_u0(u0::Vector{Float64}, p::SimulationModel{Float64, Float64}, t0::Float64)
        @ DiffEqBase .julia\packages\DiffEqBase\SaKTs\src\forwarddiff.jl:114
 [107439] get_concrete_problem(prob::ODEProblem{Vector{Float64}, Tuple{Float64, Float64}, true, SimulationModel{Float64, Float64}, ODEFunction{true, typeof(Modia.derivatives!), LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing}, Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, SciMLBase.StandardODEProblem}, isadapt::Bool; kwargs::Base.Pairs{Symbol, Any, NTuple{12, Symbol}, NamedTuple{(:u0, :p, :reltol, :abstol, :save_everystep, :callback, :adaptive, :saveat, :dt, :dtmax, :tstops, :initializealg), Tuple{Vector{Float64}, SimulationModel{Float64, Float64}, Float64, Float64, Bool, CallbackSet{Tuple{}, Tuple{DiscreteCallback{DiffEqCallbacks.var"#27#28", DiffEqCallbacks.FunctionCallingAffect{typeof(Modia.outputs!), DataStructures.BinaryMinHeap{Float64}, Vector{Float64}}, typeof(DiffEqCallbacks.functioncalling_initialize), typeof(SciMLBase.FINALIZE_DEFAULT)}, DiscreteCallback{typeof(Modia.timeEventCondition!), typeof(Modia.affectTimeEvent!), typeof(SciMLBase.INITIALIZE_DEFAULT), typeof(SciMLBase.FINALIZE_DEFAULT)}}}, Bool, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, Float64, Float64, Tuple{Float64}, NoInit}}})
        @ DiffEqBase .julia\packages\DiffEqBase\SaKTs\src\solve.jl:805
 [107440] solve_up(prob::ODEProblem{Vector{Float64}, Tuple{Float64, Float64}, true, SimulationModel{Float64, Float64}, ODEFunction{true, typeof(Modia.derivatives!), LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing}, Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, SciMLBase.StandardODEProblem}, sensealg::Nothing, u0::Vector{Float64}, p::SimulationModel{Float64, Float64}, args::Tsit5{typeof(OrdinaryDiffEq.trivial_limiter!), typeof(OrdinaryDiffEq.trivial_limiter!), Static.False}; kwargs::Base.Pairs{Symbol, Any, NTuple{10, Symbol}, NamedTuple{(:reltol, :abstol, :save_everystep, :callback, :adaptive, :saveat, :dt, :dtmax, :tstops, :initializealg), Tuple{Float64, Float64, Bool, CallbackSet{Tuple{}, Tuple{DiscreteCallback{DiffEqCallbacks.var"#27#28", DiffEqCallbacks.FunctionCallingAffect{typeof(Modia.outputs!), DataStructures.BinaryMinHeap{Float64}, Vector{Float64}}, typeof(DiffEqCallbacks.functioncalling_initialize), typeof(SciMLBase.FINALIZE_DEFAULT)}, DiscreteCallback{typeof(Modia.timeEventCondition!), typeof(Modia.affectTimeEvent!), typeof(SciMLBase.INITIALIZE_DEFAULT), typeof(SciMLBase.FINALIZE_DEFAULT)}}}, Bool, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, Float64, Float64, Tuple{Float64}, NoInit}}})
        @ DiffEqBase .julia\packages\DiffEqBase\SaKTs\src\solve.jl:725
```

From the stacktrace

```julia
 [107438] promote_u0(u0::Vector{Float64}, p::SimulationModel{Float64, Float64}, t0::Float64)
```

it seems that that `promote_u0(..., p::SimulationModel{Float64, Float64}, ..)` is called which calls forwarddiff.jl. So, something seems to be prepared for analytic differentiation. The problem is that "p" is a complex struct and it is unlikely that forwarddiff.jl can handle it.

I hope you can give advice what to do.

**Comment by MartinOtter** [comment]
It seems DiffEqBase 6.91.0 is the problem. 

I introduced the rule
```
DiffEqBase = "= 6.90.0"
```
in the Modia Project.tom file in the [compat] section to require version 6.90.0 of DiffEqBase. 
The Stackoverflow is then gone.

**Comment by ChrisRackauckas** [comment]
Can you share an MWE?

**Comment by MartinOtter** [comment]
> Can you share an MWE?

I am not sure what MWE means, but probably a runnable example that demonstrates the issue:

```julia
using Modia
include("$(Modia.path)/test/TestFirstOrder.jl")
```

I can also try to make tomorrow an as minimal example as possible, just using DifferentialEquations.jl (using a struct as "p").

**Comment by ChrisRackauckas** [comment]
This should be fixed with DiffEqBase v6.91.7. Please try that patch which opts Modules out from the system. Module and Ptr are now tested, so I believe I've covered all of the Base types + composite types in the test suite, but your case is a good case to see if all are handled.

**Comment by MartinOtter** [comment]
Thanks very much. v6.91.7 fixed the stack overflow.

**Comment by MartinOtter** [comment]
All Modia test models are simulating.
Unfortunately the StackOverflowError still appears for **Modia3D**. For example:

```julia
]add Modia3D
using Modia3D
include("$(Modia3D.path)/test/Basic/Pendulum.jl")
```

gives a stack overflow error (using the latest DiffEqBase version v.92.0).

Modia3D is a special case of Modia, that is, derivatives(du, u, p, t) has a p that is a mutable struct. The essential difference to Modia models is that in Modia3D the element *p.evaluatedParameters* is a hierarchical dictionary and values in these dictionaries are *instances of mutable structs*. I do not see other differences to Modia models that can be the reason for the StackOverflowError.

**Comment by ChrisRackauckas** [comment]
>  The essential difference to Modia models is that in Modia3D the element p.evaluatedParameters is a hierarchical dictionary and values in these dictionaries are instances of mutable structs. I do not see other differences to Modia models that can be the reason for the StackOverflowError.

No, the essential difference is that Modia3D models have circular references, i.e. they contain `::Any` struct fields and `Vector{Any}` which then reference themselves, meaning that "diving to the bottom" of the type is an infinite recursion. Some MWE examples of this behavior:

```julia
using DiffEqBase

x = Any[[1.0,2.0]]
push!(x,x)
DiffEqBase.anyeltypedual(x)

struct X; x::Any end
x = Any[[1.0,2.0]]
push!(x,X(x))
DiffEqBase.anyeltypedual(x)

mutable struct Y; x::Any end
x = Y(1)
x.x = x
DiffEqBase.anyeltypedual(x)
```

While I fix this in https://github.com/SciML/DiffEqBase.jl/pull/788, I think the lack of type-stability will inhibit performance, and in general, circular references should probably be avoided.

**Comment by MartinOtter** [comment]
Thanks, the StackOverflowError does no longer occur for Modia3D.

> Modia3D models have circular references

You are right, there is a circular reference (world has feature Scene which references world). This was introduced to just have one concept ("coordinate system with a feature"). Having two concepts - scene and coordinate-system-with-feature has other drawbacks. We did not yet recognize an issue with this circular reference, so I am unsure what to do.

>  I think the lack of type-stability will inhibit performance

In general you a right. However, Modia3D is a bit different: It constructs multi-body systems in a data structure, without compiling equations (as in Modia). This can only be done with Any-types and is super-fast (as compared with generating equations and compiling these equations). Once constructed, just a fixed set of functions is called operating on this data structure (so the functions are independent of the constructed multi-body system, and need to be compiled just once - independent of the concrete multi-body system) and these functions are type-stable. The standard technique of Julia would use dynamic dispatch (which is slow and allocates a lot of memory if called many times in a simulation). In Modia3D, dynamic dispatch is avoided by using enumerations and if-clauses to explicitly select the "right" type at run-time. All this means that time-to-start-simulation (similar to time-to-first-plot) is much faster as with equation-oriented modeling a la Modelica/Modia and the simulation it self is similar in speed (for the same functionality).
